### ISSUE TITLE
Tarkbot not starting

### ISSUE THREAD

**Issue by kihnix** [matthewmiglio/py-TarkBot#16]
Whenever I launch the bot, it presents me with this and nothing more.
![image](https://user-images.githubusercontent.com/46638658/213882880-25c6b210-433c-4d9e-ba84-77a6d709c5d9.png)

**Comment by marmig0404** [comment]
I believe this issue is a problem with how the program finds the path to the BSGLauncher executable.
There's a [new pre-release](https://github.com/matthewmiglio/py-TarkBot/releases/tag/v0.2.6rc1) available which has a fix for this.
