### ISSUE TITLE
Gets stuck at tarkov main

### ISSUE THREAD

**Issue by Haldim** [matthewmiglio/py-TarkBot#20]
Settings are correct:  windowed 4:3 run in admin mode.

![image](https://user-images.githubusercontent.com/123126636/214199722-7cf932bb-4fa2-4db7-a1cf-0ee0a591a2c4.png)

**Comment by matthewmiglio** [comment]
What things does the bot do before stopping? Does it launch the Tarkov client properly? Does the Tarkov client window move itself to the top-left?

Also which version are you using?

**Comment by Haldim** [comment]
tried on 0.2.5 & 0.2.6

bot launches everything correctly, moves everything correctly.

When I had first ran 0.2.5 it worked correctly until I stopped it.  After stopping it that time, it now continues to get stuck at "made it to tarkov main" on both version.

**Comment by Haldim** [comment]
Got it to work by fully clearing out some lingering files and reinstalling.

**Comment by marmig0404** [comment]
> Got it to work by fully clearing out some lingering files and reinstalling.

This is interesting, did you delete the whole program folder?
[The installer used](https://github.com/marcelotduarte/cx_Freeze) should handle overwriting files correctly.

**Comment by Haldim** [comment]
Correct, deleted the whole program folder just on a whim to see if that was it.  Previously I had tried to remove using the installer, as well as repairing from installer.  Neither of those options fixed it for me.

**Comment by marmig0404** [comment]
im going to close this issue given that the original one is fixed. i'll investigate the installer quirk and if i see it crop up more i'll open a separate issue.
