### ISSUE TITLE
Bot stopped after item filter button error

### ISSUE THREAD

**Issue by marmig0404** [matthewmiglio/py-TarkBot#25]
Running the v0.2.7 version, the bot ends on status:
`This item's filter by item button was unreadable this go-around. Finding another item.`

This error seems like it should only occur in the stash menu, but it appears it got stuck in the flea menu.

![image](https://user-images.githubusercontent.com/10036276/214916133-d3106e85-4bf3-4dcc-a9f8-225960188c32.png)

**Comment by matthewmiglio** [comment]
removed buggy patch that caused this error
